"""Assemble the HTML report: sections built here, layout in templates/.

The emitted page stays a single self-contained file: the stylesheet
(static/report.css) and hover script (static/report.js) are read at render
time and inlined, chart SVG is generated by charts.py, and the hover
payloads are embedded as one JSON block.
"""

from __future__ import annotations

import json
import pathlib

from jinja2 import Environment, FileSystemLoader
from markupsafe import Markup

from . import charts
from .trace import downsample, fmt_us, load, stats

_PKG = pathlib.Path(__file__).resolve().parent


def _env():
    env = Environment(loader=FileSystemLoader(_PKG / "templates"),
                      autoescape=True)
    env.filters["us"] = fmt_us
    return env


def render(trace_path, out_path):
    systems, ticks, waves = load(trace_path)
    tick_ids = sorted(ticks)
    tick_vals = [ticks[t] for t in tick_ids]
    ts = stats(tick_vals)
    n_ticks = len(tick_ids)

    payload = {"lines": {}, "hists": {}, "hbars": {}}

    def line_section(xs, ys, lo, hi, chart_id, label):
        svg, data = charts.line_chart(xs, ys, lo, hi, chart_id)
        data["label"] = label
        payload["lines"][chart_id] = data
        return Markup(svg), lo is not None

    # headline ---------------------------------------------------------------
    tiles = [
        ("mean tick", fmt_us(ts["mean"])),
        ("p50 tick", fmt_us(ts["p50"])),
        ("p99 tick", fmt_us(ts["p99"])),
        ("ticks / s", f"{1e6 / ts['mean']:,.0f}" if ts["mean"] else "0"),
    ]

    # tick wall time ----------------------------------------------------------
    tick_svg, tick_banded = line_section(
        *downsample(tick_ids, tick_vals), "tick", "tick wall")

    # waves: wall vs flush ------------------------------------------------------
    rows = []
    for w in sorted(waves):
        per_tick = waves[w].values()
        wall = sum(v[0] for v in per_tick) / len(per_tick)
        flush = sum(v[1] for v in per_tick) / len(per_tick)
        rows.append((f"wave {w}", max(0.0, wall - flush), flush))
    waves_svg, data = charts.hbars(rows, "waves", stacked=True)
    payload["hbars"]["waves"] = data

    # systems overview: amortized over the whole run (sum / ticks), so a
    # one-shot setup system compares honestly against every-tick systems.
    order = sorted(systems, key=lambda n: -sum(systems[n]["busy"]))
    rows = [(name, sum(systems[name]["busy"]) / n_ticks) for name in order]
    overview_svg, data = charts.hbars(rows, "sys")
    payload["hbars"]["sys"] = data

    # per-system cards -----------------------------------------------------------
    cards = []
    table = []
    for idx, name in enumerate(order):
        s = systems[name]
        st = stats(s["busy"])
        prep = sum(s["prep"]) / len(s["prep"])
        fin = sum(s["fin"]) / len(s["fin"])
        share = 100.0 * st["mean"] / ts["mean"] if ts["mean"] else 0
        hist_svg, hdata = charts.histogram(s["busy"], f"h-s{idx}")
        hdata["label"] = name
        payload["hists"][f"h-s{idx}"] = hdata
        series_svg, _ = line_section(*downsample(s["ticks"], s["busy"]),
                                     f"l-s{idx}", f"{name} busy")
        cards.append(dict(
            name=name, wave=s["wave"], items=s["items"], n=st["n"],
            share=f"{share:.1f}",
            ran_partial=st["n"] < n_ticks,
            stats=[("mean", fmt_us(st["mean"])), ("sd", fmt_us(st["sd"])),
                   ("p50", fmt_us(st["p50"])), ("p99", fmt_us(st["p99"])),
                   ("max", fmt_us(st["mx"])), ("prepare", fmt_us(prep)),
                   ("finish", fmt_us(fin))],
            hist=Markup(hist_svg), series=series_svg,
        ))
        table.append([name, s["wave"], s["items"], st["n"],
                      fmt_us(st["mean"]), fmt_us(st["sd"]), fmt_us(st["p50"]),
                      fmt_us(st["p99"]), fmt_us(st["mx"]), fmt_us(prep),
                      fmt_us(fin), f"{share:.1f}%"])

    doc = _env().get_template("report.html.j2").render(
        source=str(trace_path),
        n_ticks=n_ticks,
        n_systems=len(systems),
        n_waves=len(waves),
        tiles=tiles,
        tick_svg=tick_svg,
        tick_banded=tick_banded,
        waves_svg=Markup(waves_svg),
        overview_svg=Markup(overview_svg),
        cards=cards,
        table=table,
        css=Markup((_PKG / "static" / "report.css").read_text()),
        js=Markup((_PKG / "static" / "report.js").read_text()),
        payload=Markup(json.dumps(payload)),
    )
    with open(out_path, "w") as f:
        f.write(doc)
    return dict(bytes=len(doc), ticks=n_ticks, systems=len(systems))
